version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: ember-cli
    versions:
    - 3.24.0
    - 3.25.0
    - 3.25.1
    - 3.25.2
    - 3.25.3
    - 3.26.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.15
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: ember-cli-babel
    versions:
    - 7.23.1
    - 7.24.0
    - 7.25.0
    - 7.26.0
    - 7.26.1
    - 7.26.2
    - 7.26.3
  - dependency-name: ember-template-lint
    versions:
    - 2.18.0
    - 2.18.1
    - 2.19.0
    - 2.20.0
    - 2.21.0
    - 3.0.0
    - 3.0.1
    - 3.1.0
    - 3.1.1
    - 3.2.0
  - dependency-name: ember-source
    versions:
    - 3.24.1
    - 3.25.0
    - 3.25.1
    - 3.25.2
    - 3.25.3
    - 3.26.0
  - dependency-name: "@babel/plugin-proposal-optional-chaining"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.12.7
    - 7.13.0
    - 7.13.8
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.12.7
  - dependency-name: "@clark/eslint-config-node"
    versions:
    - 2.0.0
    - 2.1.0
  - dependency-name: "@clark/eslint-config-typescript"
    versions:
    - 2.0.0
    - 2.1.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: jquery
    versions:
    - 3.5.1
